version: "3.9"

services:
  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: "app"
      POSTGRES_PASSWORD: "!ChangeMe!"
      POSTGRES_USER: "app"
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "app", "-U", "app"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw

  app:
    image: php:8.4-cli
    container_name: todolist_webapp-app
    working_dir: /app
    volumes:
      - .:/app
    command: >
      sh -c "apt-get update && apt-get install -y libpq-dev && docker-php-ext-install pdo_pgsql && php bin/console doctrine:fixtures:load --no-interaction && php -S 0.0.0.0:8000 -t public"
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy

volumes:
  database_data: