<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260412190735 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE reset_password_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, selector VARCHAR(20) NOT NULL, hashed_token VARCHAR(100) NOT NULL, requested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7CE748AA76ED395 ON reset_password_request (user_id)');
        $this->addSql('CREATE TABLE role (role_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, role_name VARCHAR(60) NOT NULL, PRIMARY KEY (role_id))');
        $this->addSql('CREATE TABLE task (task_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, task_name VARCHAR(255) NOT NULL, task_details TEXT NOT NULL, task_datecreation DATE NOT NULL, datedeadline DATE NOT NULL, task_status VARCHAR(255) NOT NULL, tasktype_id INT DEFAULT NULL, taskgroup_id INT DEFAULT NULL, PRIMARY KEY (task_id))');
        $this->addSql('CREATE INDEX IDX_527EDB257D6EFC3 ON task (tasktype_id)');
        $this->addSql('CREATE INDEX IDX_527EDB2595FD12D0 ON task (taskgroup_id)');
        $this->addSql('CREATE TABLE task_group (taskgroup_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, taskgroup_name VARCHAR(255) NOT NULL, taskgroup_description VARCHAR(255) DEFAULT NULL, taskgroup_status VARCHAR(255) DEFAULT NULL, taskgroup_archivedTask BOOLEAN DEFAULT NULL, PRIMARY KEY (taskgroup_id))');
        $this->addSql('CREATE TABLE task_type (tasktype_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tasktype_type VARCHAR(255) NOT NULL, PRIMARY KEY (tasktype_id))');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_email VARCHAR(180) NOT NULL, user_username VARCHAR(160) NOT NULL, user_firstname VARCHAR(160) NOT NULL, user_pseudo VARCHAR(160) NOT NULL, user_birthday DATE NOT NULL, user_datecreation DATE NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, is_verified BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (user_email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE reset_password_request ADD CONSTRAINT FK_7CE748AA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB257D6EFC3 FOREIGN KEY (tasktype_id) REFERENCES task_type (tasktype_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB2595FD12D0 FOREIGN KEY (taskgroup_id) REFERENCES task_group (taskgroup_id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE reset_password_request DROP CONSTRAINT FK_7CE748AA76ED395');
        $this->addSql('ALTER TABLE task DROP CONSTRAINT FK_527EDB257D6EFC3');
        $this->addSql('ALTER TABLE task DROP CONSTRAINT FK_527EDB2595FD12D0');
        $this->addSql('DROP TABLE reset_password_request');
        $this->addSql('DROP TABLE role');
        $this->addSql('DROP TABLE task');
        $this->addSql('DROP TABLE task_group');
        $this->addSql('DROP TABLE task_type');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
