<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260408175924 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE role (role_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, role_name VARCHAR(60) NOT NULL, PRIMARY KEY (role_id))');
        $this->addSql('CREATE TABLE task (task_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, task_name VARCHAR(255) NOT NULL, task_details TEXT NOT NULL, task_datecreation DATE NOT NULL, datedeadline DATE NOT NULL, task_status VARCHAR(255) NOT NULL, tasktype_id INT DEFAULT NULL, PRIMARY KEY (task_id))');
        $this->addSql('CREATE INDEX IDX_527EDB257D6EFC3 ON task (tasktype_id)');
        $this->addSql('CREATE TABLE task_group (taskgroup_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, taskgroup_name VARCHAR(255) NOT NULL, taskgroup_description VARCHAR(255) NOT NULL, taskgroup_status VARCHAR(255) NOT NULL, taskgroup_archivedTask BOOLEAN NOT NULL, PRIMARY KEY (taskgroup_id))');
        $this->addSql('CREATE TABLE task_type (tasktype_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tasktype_type VARCHAR(255) NOT NULL, PRIMARY KEY (tasktype_id))');
        $this->addSql('CREATE TABLE utilisateur (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, prenom VARCHAR(255) NOT NULL, date_naissance DATE NOT NULL, speudo VARCHAR(255) NOT NULL, mot_de_passe VARCHAR(255) NOT NULL, role VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB257D6EFC3 FOREIGN KEY (tasktype_id) REFERENCES task_type (tasktype_id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE task DROP CONSTRAINT FK_527EDB257D6EFC3');
        $this->addSql('DROP TABLE role');
        $this->addSql('DROP TABLE task');
        $this->addSql('DROP TABLE task_group');
        $this->addSql('DROP TABLE task_type');
        $this->addSql('DROP TABLE utilisateur');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
